apiVersion: apps/v1
kind: Deployment
metadata: 
 name: dingtalk-hook
 namespace: zzy
spec: 
 selector:
   matchLabels:
     app: dingtalk-hook
 template:
  metadata:
   labels:
    app: dingtalk-hook
  spec: 
   containers:
   - name: dingtalk-hook
     image: app/v1:latest 
     imagePullPolicy: IfNotPresent 
     ports: 
     - containerPort: 5000
       name: http 
     env:
     - name: ROBOT_TOKEN 
       valueFrom: 
         secretKeyRef: 
           name: dingtalk-secret 
           key: token
     resources: 
      requests:
       cpu: 50m 
       memory: 100Mi
      limits:
       cpu: 50m
       memory: 100Mi
--- 
apiVersion: v1 
kind: Service
metadata:
 name: dingtalk-hook 
 namespace: zzy 
spec: 
 selector: 
   app: dingtalk-hook 
 ports: 
 - name: hook 
   port: 5000 
   targetPort: http